import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Cabin } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const utmBanque = localFont({
  src: [
    { path: "../../public/assets/fonts/00039-UTM-BanqueR.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-utm-banque",
  display: "swap",
});

const icielRukola = localFont({
  src: [
    { path: "../../public/assets/fonts/ICIEL-Rukola.otf", weight: "400", style: "normal" },
  ],
  variable: "--font-iciel-rukola",
  display: "swap",
});

const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"], // thêm 'latin-ext' hoặc 'vietnamese' nếu font hỗ trợ
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${utmBanque.variable} ${icielRukola.variable} ${cabin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
